/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EntityDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co7217/week18/entity/parser/antlr/internal/InternalEntityDsl.tokens");
	}
}
