/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.ide;

import co7217.week18.entity.EntityDslRuntimeModule;
import co7217.week18.entity.EntityDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntityDslIdeSetup extends EntityDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntityDslRuntimeModule(), new EntityDslIdeModule()));
	}
	
}
