/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntityDslStandaloneSetup extends EntityDslStandaloneSetupGenerated {

	public static void doSetup() {
		new EntityDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
