/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDslRuntimeModule extends AbstractEntityDslRuntimeModule {
}
