/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.web;

import co7217.week18.entity.EntityDslRuntimeModule;
import co7217.week18.entity.EntityDslStandaloneSetup;
import co7217.week18.entity.ide.EntityDslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class EntityDslWebSetup extends EntityDslStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntityDslRuntimeModule(), new EntityDslIdeModule(), new EntityDslWebModule()));
	}
	
}
