/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class EntityDslWebModule extends AbstractEntityDslWebModule {
}
