/**
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.entityDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co7217.week18.entity.entityDsl.EntityDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
