/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link EntityDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractEntityDslWebModule extends DefaultWebModule {

}
