/*
 * generated by Xtext 2.32.0
 */
package co7217.week18.entity.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntityDslScopeProvider extends DelegatingScopeProvider {
}
